### ISSUE TITLE
Rapid changes to the API

### ISSUE THREAD

**Issue by ArneBachmannDLR** [keithasaurus/koda#21]
I love this project!
Just noticed that the library had a few changes that broke my tests:

- 1.2.0: `OK(val=...)`
- 1.3.x: `<koda.result.Ok object at 0x0000017B109DBB80>`
- 1.4.0 `Ok(...)`

I guess the latest is the best :-)

**Comment by keithasaurus** [comment]
@ArneBachmannDLR Terribly sorry about this! Further changes won't be so rapid. FWIW the work that was done was to make many class instances in koda instantiate faster (in service of https://github.com/keithasaurus/koda-validate).

I didn't consider repr changes to be breaking, so didn't bump the major version -- apologies!

Thanks for reporting this.

**Comment by ArneBachmannDLR** [comment]
No worries!
