### ISSUE TITLE
[question] Is there a preferred way to encode the "unit" type?

### ISSUE THREAD

**Issue by yanniskatsaros** [keithasaurus/koda#22]
Hello there, thank you for the work you've done on this project!

I was curious if there was a supported or preferred way to encode the unit type `()` within `koda` which is commonly found in many functional programming languages? I realize that `()` works syntactically in Python but it represents the empty tuple rather than unit. Alternatively, I suppose use of `None` could also be used instead of `Unit` but the issue is this won't work with common type checking tools like `mypy`/`pyre`/`pyright` etc. I looked around the source code to see if there was something similar to how `nothing` is defined but for `unit` but couldn't find anything.

It would be great to be able to write something like:

```python
def example(...) -> Result[Unit, str]:
    if ...:
        return Ok(())
    else:
        return Err("something went wrong")
```

Do you have any advice on how to do this? If this is something you'd be interested in adding I would be happy to contribute. Thank you in advance for any insights!

**Comment by keithasaurus** [comment]
For the empty tuple interpretation, pep 484 says you can do `x: tuple[()]  = ()`. And this does type-check in mypy. For the result example, I'd probably use `Result[None, str]`, but more likely I'd just do `Maybe[str]`:

```python
def example(...) -> Maybe[str]:
  if ...:
      return nothing
  else:
      return Just("something went wrong")
```
Depends on what you want to do.

For more general validation, there is a companion library to koda called 9koda-validate](https://github.com/keithasaurus/koda-validate).
